---
- name: Add RHEL repository
  yum_repository:
    name: hashicorp
    description: hashicorp repository
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Install Consul
  package:
    name: consul
    state: latest
    
- name: Template for Consul configuration
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl

- name: Start Consul
  service:
    name: consul
    state: restarted
    enabled: yes
  become: yes